### ISSUE TITLE
Foreslag - Pull Requests virker ikke

### ISSUE THREAD

**Issue by OBadstue** [tokeraabjerg/LectioExpert#2]
Det ville være meget fedt hvis man kunne uploade eller linke til en billede, som så ville erstatte lectio's standard hvide baggrund. Det nuværende måde at gøre det på viser kun billedet indtil man skifter til anden fane (fx lektier) eller hvis man refresher siden. Efter det er billedet væk, og kommer ikke igen.

**Comment by tokeraabjerg** [comment]
Der var sket en fejl i implementeringen af det nye "standard baggrund". Fejlen er nu fixet i <2.8.7.

Opdateringen vil være ude I løbet af et par dage.
